/* Generated By:JJTree: Do not edit this line. ASTBooleanType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTBooleanType extends SimpleNode {
  public ASTBooleanType(int id) {
    super(id);
  }

  public ASTBooleanType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c46e285d0ef32aeabf66c1a359e52a31 (do not edit this line) */
