/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTBooleanValue extends SimpleNode {
  public ASTBooleanValue(int id) {
    super(id);
  }

  public ASTBooleanValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c1f56e6f5bea81e6e4b75dae9dfcfa7b (do not edit this line) */
