/* Generated By:JJTree: Do not edit this line. ASTBinaryString.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTBinaryString extends SimpleNode {
  public ASTBinaryString(int id) {
    super(id);
  }

  public ASTBinaryString(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2499b0491c583449cd41f6f5b93b2d83 (do not edit this line) */
