/* Generated By:JJTree: Do not edit this line. ASTCompoundValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTCompoundValue extends SimpleNode {
  public ASTCompoundValue(int id) {
    super(id);
  }

  public ASTCompoundValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d6ea09d51658763d82ae506dcb9fd3ff (do not edit this line) */
