/* Generated By:JJTree: Do not edit this line. ASTClass.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public class ASTClass extends SimpleNode {

	private int tc = ASTTaggedType.CONTEXT;

	public void
	setTagClass(int x)
	{
		tc = x;
	}

	public int
	getTagClass()
	{
		return tc;
	}

  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4707e764a373a498e5868ca872a44345 (do not edit this line) */
