/* Generated By:JJTree: Do not edit this line. ASTComponentsType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTComponentsType extends SimpleNode {
  public ASTComponentsType(int id) {
    super(id);
  }

  public ASTComponentsType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=81899cfc0b4da1eb1c7d8f4065f8f020 (do not edit this line) */
