/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroName.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTDefinedMacroName extends SimpleNode {
  public ASTDefinedMacroName(int id) {
    super(id);
  }

  public ASTDefinedMacroName(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=573b039f121501c05f2955fa62df60c7 (do not edit this line) */
