/* Generated By:JJTree: Do not edit this line. ASTDisplayHint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTDisplayHint extends SimpleNode {
  public ASTDisplayHint(int id) {
    super(id);
  }

  public ASTDisplayHint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7a14d7d6648d493d1884cf79eb71332d (do not edit this line) */
