/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTDefinedMacroType extends SimpleNode {
  public ASTDefinedMacroType(int id) {
    super(id);
  }

  public ASTDefinedMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be9dd9b1ff6899936f6973b6c682ecd3 (do not edit this line) */
