/* Generated By:JJTree: Do not edit this line. ASTEnumerationItem.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTEnumerationItem extends SimpleNode {
  public ASTEnumerationItem(int id) {
    super(id);
  }

  public ASTEnumerationItem(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0caca1fb820bd342872ff59a8e67171b (do not edit this line) */
