/* Generated By:JJTree: Do not edit this line. ASTEnumeratedType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTEnumeratedType extends SimpleNode {
  public ASTEnumeratedType(int id) {
    super(id);
  }

  public ASTEnumeratedType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92eb9bc0a0b03106d9cc080ff11a46e4 (do not edit this line) */
