/* Generated By:JJTree: Do not edit this line. ASTMacroBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTMacroBody extends SimpleNode {
  public ASTMacroBody(int id) {
    super(id);
  }

  public ASTMacroBody(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0233d71f5336ff48d1138d48e9f51e7b (do not edit this line) */
