/* Generated By:JJTree: Do not edit this line. ASTmodulereference.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTmodulereference extends SimpleNode {
  public ASTmodulereference(int id) {
    super(id);
  }

  public ASTmodulereference(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0e08cfc42c66a2a788399377e42f8e1 (do not edit this line) */
