/* Generated By:JJTree: Do not edit this line. ASTModuleDefinition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTModuleDefinition extends SimpleNode {
  public ASTModuleDefinition(int id) {
    super(id);
  }

  public ASTModuleDefinition(AsnParser p, int id) {
    super(p, id);
  }

    @Override
    public String getModuleId(){
        if (moduleId == null) {
            for (int i = 0; i < children.length; ++i) {
                SimpleNode n = (SimpleNode)children[i];
                if (n instanceof ASTModuleIdentifier) {
                    moduleId = n.jjtGetFirstToken().image;
                }
            }
        }
        return moduleId;
    }

  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c09c4255e1c7b0fe76d205612a6c3383 (do not edit this line) */
