/* Generated By:JJTree: Do not edit this line. ASTMacroDefinition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTMacroDefinition extends SimpleNode {
  public ASTMacroDefinition(int id) {
    super(id);
  }

  public ASTMacroDefinition(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a993b76098224db54db64f1989884159 (do not edit this line) */
