/* Generated By:JJTree: Do not edit this line. ASTNamedNumberList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTNamedNumberList extends SimpleNode {
  public ASTNamedNumberList(int id) {
    super(id);
  }

  public ASTNamedNumberList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57bba68513e7bddd324cd3364d7dc3f2 (do not edit this line) */
