/* Generated By:JJTree: Do not edit this line. ASTNamedValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTNamedValue extends SimpleNode {
  public ASTNamedValue(int id) {
    super(id);
  }

  public ASTNamedValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=adf0fc6baaacf3c6a286c265615bf867 (do not edit this line) */
