/* Generated By:JJTree: Do not edit this line. ASTObjIdComponent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTObjIdComponent extends SimpleNode {
  public ASTObjIdComponent(int id) {
    super(id);
  }

  public ASTObjIdComponent(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a20a39e1bf4c16bd8241db48cdf15a1 (do not edit this line) */
