/* Generated By:JJTree: Do not edit this line. ASTObjectIdentifierValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTObjectIdentifierValue extends SimpleNode {
  public ASTObjectIdentifierValue(int id) {
    super(id);
  }

  public ASTObjectIdentifierValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc91b55788d4be9857477d8563a7928e (do not edit this line) */
