/* Generated By:JJTree: Do not edit this line. ASTPresenceConstraint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTPresenceConstraint extends SimpleNode {
  public ASTPresenceConstraint(int id) {
    super(id);
  }

  public ASTPresenceConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=343b8de44a487d0d9e5d9cb962d4afa3 (do not edit this line) */
