/* Generated By:JJTree: Do not edit this line. ASTSingleTypeConstraint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSingleTypeConstraint extends SimpleNode {
  public ASTSingleTypeConstraint(int id) {
    super(id);
  }

  public ASTSingleTypeConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=062ea9d2682435ea474b6fc3bbc90744 (do not edit this line) */
