/* Generated By:JJTree: Do not edit this line. ASTSizeConstraint.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSizeConstraint extends SimpleNode {
  public ASTSizeConstraint(int id) {
    super(id);
  }

  public ASTSizeConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0387c21444a57ba6c1029d881b051ee1 (do not edit this line) */
