/* Generated By:JJTree: Do not edit this line. ASTSnmpObjectTypeMacroType.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSnmpObjectTypeMacroType extends SimpleNode {
  public ASTSnmpObjectTypeMacroType(int id) {
    super(id);
  }

  public ASTSnmpObjectTypeMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a892e087ee61acbc7670f7a342c9b8a (do not edit this line) */
