/* Generated By:JJTree: Do not edit this line. ASTSnmpReferPart.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSnmpReferPart extends SimpleNode {
  public ASTSnmpReferPart(int id) {
    super(id);
  }

  public ASTSnmpReferPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa69f0423943202e75e252c84db18402 (do not edit this line) */
