/* Generated By:JJTree: Do not edit this line. ASTSnmpDefValPart.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSnmpDefValPart extends SimpleNode {
  public ASTSnmpDefValPart(int id) {
    super(id);
  }

  public ASTSnmpDefValPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=838bc9eeb12934f07fab214881414dbd (do not edit this line) */
