/* Generated By:JJTree: Do not edit this line. ASTSubtypeValueSet.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSubtypeValueSet extends SimpleNode {
  public ASTSubtypeValueSet(int id) {
    super(id);
  }

  public ASTSubtypeValueSet(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f6c6a129ceddebcda604cc61d5d2617 (do not edit this line) */
