/* Generated By:JJTree: Do not edit this line. ASTSymbolsImported.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSymbolsImported extends SimpleNode {
  public ASTSymbolsImported(int id) {
    super(id);
  }

  public ASTSymbolsImported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5e04f27803e95876b3ce3ad7961dc387 (do not edit this line) */
