/* Generated By:JJTree: Do not edit this line. ASTSymbolsExported.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSymbolsExported extends SimpleNode {
  public ASTSymbolsExported(int id) {
    super(id);
  }

  public ASTSymbolsExported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ab9ddb80fb7ed9ff694c3c86cf9a472c (do not edit this line) */
