/* Generated By:JJTree: Do not edit this line. ASTSymbolsFromModuleList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSymbolsFromModuleList extends SimpleNode {
  public ASTSymbolsFromModuleList(int id) {
    super(id);
  }

  public ASTSymbolsFromModuleList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0269c3a00848601c4109098da1d64199 (do not edit this line) */
