/* Generated By:JJTree: Do not edit this line. ASTSubtypeSpec.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTSubtypeSpec extends SimpleNode {
  public ASTSubtypeSpec(int id) {
    super(id);
  }

  public ASTSubtypeSpec(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=48b6637fdd86f971e7dada43cf7c8684 (do not edit this line) */
