/* Generated By:JJTree: Do not edit this line. ASTTypeAssignment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTTypeAssignment extends SimpleNode {
  public ASTTypeAssignment(int id) {
    super(id);
  }

  public ASTTypeAssignment(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7b53efbddcd08baa8b28d32e1ac9627 (do not edit this line) */
