/* Generated By:JJTree: Do not edit this line. ASTTypeConstraints.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javacc;

public
class ASTTypeConstraints extends SimpleNode {
  public ASTTypeConstraints(int id) {
    super(id);
  }

  public ASTTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a22a53917b83f1363161fc3b0a18c5c0 (do not edit this line) */
